apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actions-runner-system

resources:
- github.com/actions/actions-runner-controller/tree/v0.22.2/config/default
- ingress.yaml

patchesStrategicMerge:
- https://raw.githubusercontent.com/actions/actions-runner-controller/refs/tags/v0.22.2/config/default/manager_auth_proxy_patch.yaml
